### ISSUE TITLE
ValueError: math domain error acos()

### ISSUE THREAD

**Issue by maxchepurko** [Robotics-Technology/Chess-Robot#6]
Hello!
I use your guide to set up and play chess with the LSS 4 Of Robotic Arm robot.
After setting up the chessboard parameters:
Base Radius 9.00
Chess Board Frame 8.00
Square Size 1.00
ChessBoard Height 0.75
Tallest Piece Height 2.25

and calibrating the camera and launching the game - I get an error:

"...
Exception in thread Thread-2 (pcTurn):
Traceback (most recent call last):
File "C:\Users\chepu\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\Users\chepu\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "C:\LSS_Chess_Robot\Chess-Robot\Interface.py", line 137, in pcTurn
ac.executeMove(sequence["seq"], physicalParams, playerColor, homography, cap, selectedCam)
File "C:\LSS_Chess_Robot\Chess-Robot\ArmControl.py", line 213, in executeMove
angles_BSEWG1 = LSS_IK([x, y, z + 1, gripState])
File "C:\LSS_Chess_Robot\Chess-Robot\ArmControl.py", line 76, in LSS_IK
a2 = acos((d2**2 - d3**2 + h**2)/(2 * d2 * h))
ValueError: math domain error

Incorrect mathematical calculations - the system tries to calculate acos(1.58) and therefore gets an error

Tell me what this could mean and what am I doing wrong?

**Comment by geraldinebc** [comment]
Hello! This means that the arm can't reach the desired position, this is due to setting the parameters incorrectly. The base radius should be the measurement between the center of the arm's base and the chessboard. The chessboard frame should be the measurement of the frame of your chessboard (most likely smaller or similar to the square size). Also, keep in mind that these measurements are in inches.

**Comment by maxchepurko** [comment]
Thank you, you're right - the problem was in the parameters. I measured it again, this error is gone.
